apiVersion: apps/v1
kind: Deployment
metadata:
  name: cutter-status-dashboard
  namespace: default
  labels:
    app.kubernetes.io/instance: cutter-status-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cutter-status-dashboard
  template:
    metadata:
      labels:
        app: cutter-status-dashboard
    spec:
      imagePullSecrets:
        - name: cutter-prod-gcr-regcred
      volumes:
        - name: service-account
          secret:
            secretName: "cutter-prod-idp-key"
        - name: cutter-prod-sql-proxy-sa
          secret:
            secretName: cutter-prod-sql-proxy-sa
      terminationGracePeriodSeconds: 60  
      containers:
      - name: cutter-status-dashboard
        image: "gcr.io/$PROJECT_ID/cutter-status-dashboard:$TAG"
        args:
            - --cooldown=1800
            - --log=error-log-sink-$ENV
        imagePullPolicy: Always
        volumeMounts:
          - name: service-account
            mountPath: /keys/
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
            - name: http
              containerPort: 8080
              protocol: TCP
        livenessProbe:
            httpGet:
              scheme: HTTP
              path: /healthcheck
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /healthcheck
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
        env: 
          - name: GOOGLE_PROJECT
            value: $PROJECT_ID
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: $GOOGLE_APPLICATION_CREDENTIALS
          - name: PORT
            value: "8080"
          - name: DB_HOSTNAME
            value: localhost
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cutter-prod-status-dashboard-secrets
                key: DB_PASSWORD
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: cutter-prod-status-dashboard-secrets
                key: DB_USERNAME
          - name: DB_NAME 
            value: cutter-prod-status-dashboard
          - name: DB_PORT
            value: "5432"
          - name: MIGRATE_LEVEL 
            value: "up"
          - name: MIGRATIONS_FOLDER
            value: /app/migrations
          - name: PLATFORM_ENDPOINT
            value: "https://cutter-prod-platform-api-service"
          - name: FULFILLMENT_ENDPOINT
            value: "https://cutter-prod-fulfillment-service-service"
          - name: CRM_ENDPOINT
            value: "https://cutter-prod-crm-service-service"
          - name: STUDY_ENDPOINT
            value: "https://cutter-prod-study-service-service"
          - name: CLUSTER_NAME
            value: "cutter-prod-gke-cluster"
          - name: BUCKET_NAME
            value: "dashboard-prod-service-report"
          - name: HIBBERT_ENDPOINT
            value: "https://inventoryservices.qa.order2u.com/restServices/getUserToken"
          - name: APP_ID
            value: "3142"
          - name: HIBBERT_USERNAME
            valueFrom:
              secretKeyRef:
                name: cutter-prod-status-dashboard-secrets
                key: HIBBERT_USERNAME
          - name: HIBBERT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cutter-prod-status-dashboard-secrets
                key: HIBBERT_PASSWORD
          - name: STRIPE_ENDPOINT
            value: "https://api.stripe.com/v1/charge"
          - name: STRIPE_KEY
            valueFrom:
              secretKeyRef:
                name: cutter-prod-status-dashboard-secrets
                key: STRIPE_KEY
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: cutter-prod-status-dashboard-secrets
                key: CLIENT_ID
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: cutter-prod-status-dashboard-secrets
                key: CLIENT_SECRET
          - name: AZ_CRM_URL
            value: "https://identityapiqa.a.astrazeneca.com"
          - name: X_APP_ID
            value: "SYSTEM" 
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.14
        resources:
          requests:
            cpu: 100m
        env:
          - name: DB_HOSTNAME
            value: localhost
          - name: ENV
            value: prod
        command:
          - /cloud_sql_proxy
          - -instances=cutter-prod:us-central1:cutter-prod-dashboard=tcp:5432
          - -credential_file=/secrets/cloudsql/credentials.json
          - ./cloudbuild/migrations
        securityContext:
          runAsUser: 2 # non-root user
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: cutter-prod-sql-proxy-sa
            mountPath: /secrets/cloudsql
            readOnly: true
--- 
apiVersion: v1
kind: Service
metadata:
  name: cutter-status-dashboard
  labels:
    app: cutter-status-dashboard
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: cutter-status-dashboard
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
